# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.6
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # CS3513 Exercise 3
#
# Due 2/28/2025.   
# Last possbile submission : 3/14/2025.
#
# See exercise3.pdf for problem descriptions.
#

# %%
from math import cos, sin
import matplotlib.pyplot as plt
import numpy as np
import scipy
import scipy.optimize

# functions for use in the questions.
def bar(t): 
    return (t-1/3)*(t- (7+1/3))*(t- (2**10-2/3) ) *cos(t/600)

def baz(t): 
    return (t-1/3)**3*(t- (7+1/3))**3*(t- (2**10 -2/3) )**3 *cos(t/600)

# first derviatives generated by gendiffEx3.py
def diff_bar(z):    
    return -(z - 1023.33333333333)*(z - 7.33333333333333)*(z - 0.333333333333333)*sin(z/600)/600 + (z - 1023.33333333333)*(z - 7.33333333333333)*cos(z/600) + (z - 1023.33333333333)*(z - 0.333333333333333)*cos(z/600) + (z - 7.33333333333333)*(z - 0.333333333333333)*cos(z/600)

def diff_baz(z):
    return -704375740.88706*(0.000977198697068404*z - 1)**3*(0.136363636363636*z - 1)**3*(z - 0.333333333333333)**3*sin(z/600) + 1267876333596.71*(0.000977198697068404*z - 1)**3*(0.136363636363636*z - 1)**3*(z - 0.333333333333333)**2*cos(z/600) + 172892227308.642*(0.000977198697068404*z - 1)**3*(0.136363636363636*z - 1)**2*(z - 0.333333333333333)**3*cos(z/600) + 1238967101.23457*(0.000977198697068404*z - 1)**2*(0.136363636363636*z - 1)**3*(z - 0.333333333333333)**3*cos(z/600)



# %%
def Question1():
    # see exercise3.pdf for description
    print("Question 1")
    # add your code here
    intervals = [(0, 1), (7, 8), (1023, 1024)]
    for a, b in intervals:
        root, result = scipy.optimize.bisect(bar, a, b, xtol=1e-16, full_output=True, disp=False)
    converged = int(result.converged)

    print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("method name", "converged", "root location", "number of iterations", "number of function calls"))
    print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("bisect", converged, root, result.iterations, result.function_calls))

# %%
def Question2():
    # see exercise3.pdf for description
    print("Question 2")
    # add your code here
    intervals = [(0, 1), (7, 8), (1023, 1024)]
    print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("method name", "converged", "root location", "number of iterations", "number of function calls"))

    for a, b in intervals:
        x0 = (a + b) / 2

        root_ridder, result_ridder = scipy.optimize.ridder(bar, a, b, xtol=1e-16, full_output=True, disp=False)
        print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("ridder", int(result_ridder.converged), root_ridder, result_ridder.iterations, result_ridder.function_calls))

        root_brentq, result_brentq = scipy.optimize.brentq(bar, a, b, xtol=1e-16, full_output=True, disp=False)
        print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("brentq", int(result_brentq.converged), root_brentq, result_brentq.iterations, result_brentq.function_calls))

        root_newton, result_newton = scipy.optimize.newton(bar, x0, fprime=diff_bar, tol=1e-16, full_output=True, disp=False)
        print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("newton", int(result_newton.converged), root_newton, result_newton.iterations, result_newton.function_calls))

# %%
def Question3():
    # see exercise3.pdf for description
    print("Question 3")
    # add your code here
    plots = [
        {"func": bar, "range": (5.0, 9.0), "title": "Q3-a-bar"},
        {"func": baz, "range": (5.0, 9.0), "title": "Q3-b-baz"},
        {"func": bar, "range": (7.0, 7.5), "title": "Q3-c-bar"},
        {"func": baz, "range": (7.0, 7.5), "title": "Q3-d-baz"},
    ]
    
    for config in plots:
        t = np.linspace(config["range"][0], config["range"][1], 1000)
        vectorized_func = np.vectorize(config["func"])
        y = vectorized_func(t)
        plt.figure()
        plt.plot(t, y)
        plt.title(config["title"])
        plt.savefig(f"{config['title']}.pdf", format="pdf")
        plt.close()


# %%
def Question4():
    # see exercise3.pdf for description
    print("Question 4")
    # add your code here
    intervals = [(0, 1), (7, 8), (1023, 1024)]
    print("{:<15} {:<15} {:<25} {:<25} {:<15}".format("Method", "Converged", "Root Location", "Iterations", "Function Calls"))
    
    for a, b in intervals:
        for method in [scipy.optimize.bisect, scipy.optimize.ridder, scipy.optimize.brentq]:
            root, result = method(baz, a, b, xtol=1e-16, full_output=True, disp=False)
            print("{:<15} {:<15} {:<25} {:<25} {:<15}".format(method.__name__, int(result.converged), root, result.iterations, result.function_calls))

# %%
if __name__ == "__main__" :
    print("CS 3513, Spring 2025")
    print("Exercise 3")
    print("StudentName = ", "Eli Webb")
    print("GitHub Username = ", "eliwebb11")
    print()
    Question1()
    print()
    Question2()
    print()
    Question3()
    print()
    Question4()

